color1 = input("Color: ")
adjective1 = input("Adjective: ")
noun1 = input("Noun: ")
adjective2 = input("Adjective: ")
adjective3 = input("Adjective: ")
noun2 = input("Noun: ")
adjective4 = input("Adjective: ")
adjective5 = input("Adjective: ")
noun3 = input("Noun: ")
noun4 = input("Noun: ")
bodypart = input("Body Part: ")
verb1 = input("Verb: ")
noun5 = input("Noun: ")
pluralnoun = input("Plural Noun: ")
verb2 = input("Verb: ")
verb3 = input("Verb: ")
adjective6 = input("Adjective: ")
noun6 = input("Noun: ")
adjective7 = input("Adjective: ")

Mad_libs = "I walk through the %s jungle. I take out my %s %s canteen. There is a %s parrot with a %s %s in his mouth right in front of me in the %s trees! I gaze at his %s %s. A sudden sound awakes me from my daydream! A %s is right in front of my %s! I %s my breath. I remember I have a packet of %s that makes %s go into a deep slumber! I %s it in front of the %s.Yes he's eating it! I %s away through the %s jungle. I meet my parents at the %s. Phew; It’s been an %s day in the jungle. " % (color1, adjective1, noun1, adjective2, adjective3, noun2, adjective4, adjective5, noun3, noun4, bodypart, verb1, noun5, pluralnoun, verb2, noun4, verb3, adjective6, noun6, adjective7)
print (Mad_libs)
